# Generated by Django 4.1.3 on 2022-12-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_blogmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
